import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainRootLayout from "./MainRootLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Redux Toolkit Counter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainRootLayout>
        {children}
        </MainRootLayout>
      </body>
    </html>
  );
}
